### ISSUE TITLE
Hash tag detection seems to override URLs

### ISSUE THREAD

**Issue by kamalmarhubi** [icco/natwelch.com#12]
See your recent post https://writing.natwelch.com/post/608 for an example at the link to PR #11.

**Comment by icco** [comment]
I fixed that specific post, but yeah I really need to figure out a better way to do this.

**Comment by icco** [comment]
I've opened https://github.com/icco/natnatnat/issues/14 in the correct repo, thanks for raising this @kamalmarhubi !
